#!/bin/bash

# Qeevees-MacBook-Air-2:~ admin$ /usr/libexec/java_home -V
# Matching Java Virtual Machines (5):
#     1.8.0_131, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
#     1.8.0_05, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
#     1.7.0_79, x86_64:	"Java SE 7"	/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
#     1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
#     1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

# /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
# Qeevees-MacBook-Air-2:~ admin$ export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
# Qeevees-MacBook-Air-2:~ admin$ echo $JAVA_HOME
# /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home

echo "Starting GeoQuest Server ..."

#TODO: Check that Java 1.7 is available and set it active.
echo "  switching to Java Version 1.7 ..."
JAVA_HOME_OLD=$JAVA_HOME
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/

GQ_EDITOR_MODE_INSECURE=true
export GQ_EDITOR_MODE_INSECURE

# check wether $GQ_SERVER_PLAY_BASE_DIR is set:
if [ -z ${GQ_SERVER_PLAY_BASE_DIR+valueIfSet} ]; then
	echo "ERROR: This script assumes that you have set the environment variable GQ_SERVER_PLAY_BASE_DIR pointing to the application directory."
	echo "  exiting."
	exit -1
else
	echo " your geoquest play project home is $GQ_SERVER_PLAY_BASE_DIR"
fi

pushd $GQ_SERVER_PLAY_BASE_DIR > /dev/null

# gathering application.conf:
APP_CONF=${GQ_LOCAL_APP_CONF:-${GQ_SERVER_PLAY_BASE_DIR}/conf/application.conf}
if [ ! -f $APP_CONF ]; then
	echo "ERROR: application config file $APP_CONF not found. Exiting ..."
	exit -1
else
	echo " application config file is: $APP_CONF "
fi


# check for RUNNING_PID file:
if [ -f "RUNNING_PID" ]; then
	echo "WARNING: We kill a running server process and restart it."
	kill `cat RUNNING_PID`
fi 

#extract additional parameter:
# TODO allow multiple additional parameters
if [ $# -gt 1 ]; then
	ADDITIONAL_PARAM=$2 
	echo "  using additonal parameter: $ADDITIONAL_PARAM"
else
	ADDITIONAL_PARAM=""
	echo "  no addtitonal parameter given."
fi

# DO it:
if [ $# -gt 0 ] && [ $1 = "run" ]; then
	echo "  running play ..."
	play -Dconfig.file=$APP_CONF $ADDITIONAL_PARAM -DapplyEvolutions.default=true run
elif [ $# -gt 0 ] && [ $1 = "debug" ]; then
	echo "  running play in debug mode ..."
	play debug -Dconfig.file=$APP_CONF $ADDITIONAL_PARAM -DapplyEvolutions.default=true run
else
	echo "  starting play ..."
	play -Dconfig.file=$APP_CONF $ADDITIONAL_PARAM -DapplyEvolutions.default=true start
fi

# Afterwards:
echo "back from play."

# finally setting back to the previously used Java version and the directory we had been before:
export JAVA_HOME=$JAVA_HOME_OLD
popd > /dev/null
