#!/bin/bash

# TODO: check if env var $GQ_SERVER_PLAY_BASE_DIR is set

echo "Starting GeoQuest Server ..."

#TODO: Check that Java 1.7 is available and set it active.
echo "switching to Java Version 1.7 ..."
JAVA_HOME_OLD=$JAVA_HOME
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_25.jdk/Contents/Home/

pushd $GQ_SERVER_PLAY_BASE_DIR

# check for RUNNING_PID file:
if [ -f "RUNNING_PID" ]; then
	echo "WARNING: We kill a running server process and restart it."
	kill `cat RUNNING_PID`
fi 

if [ $# -gt 0 ] && [ $1 = "run" ]; then
	echo "running play ..."
	play run
elif [ $# -gt 0 ] && [ $1 = "debug" ]; then
	echo "running play in debug mode ..."
	play debug run
else
	echo "starting play ..."
	play start
fi

echo "back from play."

# finally setting back to the previously used Java version and the directory we had been before:
#export JAVA_HOME=$JAVA_HOME_OLD
popd
